import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { IEvent } from "@/lib/types";

// Slugs are generated by generate_event_slug() (see the events table migration)
// via lowercase letters, digits, and hyphens only.
const SLUG_PATTERN = /^[a-z0-9-]+$/;

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ slug: string }> },
) {
  const { slug } = await params;

  if (!slug || !SLUG_PATTERN.test(slug)) {
    return NextResponse.json(
      { message: "Invalid or missing event slug" },
      { status: 400 },
    );
  }

  try {
    const supabase = await createClient();

    const { data, error } = await supabase
      .from("events")
      .select("*")
      .eq("slug", slug)
      .single<IEvent>();

    if (error) {
      // PGRST116: no row matched .single() -- a genuine "not found", not a server error.
      if (error.code === "PGRST116") {
        return NextResponse.json(
          { message: `Event with slug "${slug}" not found` },
          { status: 404 },
        );
      }

      console.error("Error fetching event by slug", error);
      return NextResponse.json(
        { message: "Failed to fetch event", error: error.message },
        { status: 500 },
      );
    }

    return NextResponse.json(
      { message: "Event fetched successfully", event: data },
      { status: 200 },
    );
  } catch (error) {
    console.error("Unexpected error fetching event by slug", error);
    return NextResponse.json(
      {
        message: "Unexpected error while fetching event",
        error: error instanceof Error ? error.message : "Unknown",
      },
      { status: 500 },
    );
  }
}
