export const events = [
  {
    image: "/images/event1.png",
    title: "React Summit 2025",
    slug: "react-summit-2025",
    location: "San Francisco, CA",
    date: "2025-09-15",
    time: "09:00 AM",
  },
  {
    image: "/images/event2.png",
    title: "AI Hackathon Weekend",
    slug: "ai-hackathon-weekend",
    location: "Austin, TX",
    date: "2025-10-02",
    time: "10:00 AM",
  },
  {
    image: "/images/event3.png",
    title: "DevOps Meetup",
    slug: "devops-meetup",
    location: "Seattle, WA",
    date: "2025-08-20",
    time: "06:30 PM",
  },
  {
    image: "/images/event4.png",
    title: "Next.js Conf",
    slug: "nextjs-conf",
    location: "New York, NY",
    date: "2025-11-05",
    time: "09:30 AM",
  },
  {
    image: "/images/event5.png",
    title: "Women in Tech Summit",
    slug: "women-in-tech-summit",
    location: "Chicago, IL",
    date: "2025-09-28",
    time: "11:00 AM",
  },
  {
    image: "/images/event6.png",
    title: "Open Source Contribution Day",
    slug: "open-source-contribution-day",
    location: "Remote",
    date: "2025-10-18",
    time: "01:00 PM",
  },
];
